// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: protobufs/product.proto

package compilesReadOnly

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 响应的产品信息结构
type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsSale        bool                   `protobuf:"varint,3,opt,name=is_sale,json=isSale,proto3" json:"is_sale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_protobufs_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetIsSale() bool {
	if x != nil {
		return x.IsSale
	}
	return false
}

// 请求产品信息时的参数消息
type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_protobufs_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_protobufs_product_proto protoreflect.FileDescriptor

const file_protobufs_product_proto_rawDesc = "" +
	"\n" +
	"\x17protobufs/product.proto\"N\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\ais_sale\x18\x03 \x01(\bR\x06isSale\" \n" +
	"\x0eProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2=\n" +
	"\aProduct\x122\n" +
	"\vProductInfo\x12\x0f.ProductRequest\x1a\x10.ProductResponse\"\x00B\x14Z\x12./compilesReadOnlyb\x06proto3"

var (
	file_protobufs_product_proto_rawDescOnce sync.Once
	file_protobufs_product_proto_rawDescData []byte
)

func file_protobufs_product_proto_rawDescGZIP() []byte {
	file_protobufs_product_proto_rawDescOnce.Do(func() {
		file_protobufs_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufs_product_proto_rawDesc), len(file_protobufs_product_proto_rawDesc)))
	})
	return file_protobufs_product_proto_rawDescData
}

var file_protobufs_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufs_product_proto_goTypes = []any{
	(*ProductResponse)(nil), // 0: ProductResponse
	(*ProductRequest)(nil),  // 1: ProductRequest
}
var file_protobufs_product_proto_depIdxs = []int32{
	1, // 0: Product.ProductInfo:input_type -> ProductRequest
	0, // 1: Product.ProductInfo:output_type -> ProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_product_proto_init() }
func file_protobufs_product_proto_init() {
	if File_protobufs_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufs_product_proto_rawDesc), len(file_protobufs_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_product_proto_goTypes,
		DependencyIndexes: file_protobufs_product_proto_depIdxs,
		MessageInfos:      file_protobufs_product_proto_msgTypes,
	}.Build()
	File_protobufs_product_proto = out.File
	file_protobufs_product_proto_goTypes = nil
	file_protobufs_product_proto_depIdxs = nil
}
